### ISSUE TITLE
In a dockerized environment

### ISSUE THREAD

**Issue by sztojkatamas** [bitmill/apitester#1]
root@c76e0eed4b3c:/home/kissrichard# python apitester.py 10 "http://www.sg.hu"
FETCHING URL >>> 'http://www.sg.hu'
Traceback (most recent call last):
  File "apitester.py", line 66, in <module>
    print(generateReq.request_processing())
  File "apitester.py", line 43, in request_processing
    json_obj = response.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
root@c76e0eed4b3c:/home/kissrichard# python apitester.py 100 "http://www.index.hu"
FETCHING URL >>> 'http://www.index.hu'
Traceback (most recent call last):
  File "apitester.py", line 66, in <module>
    print(generateReq.request_processing())
  File "apitester.py", line 43, in request_processing
    json_obj = response.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
root@c76e0eed4b3c:/home/kissrichard#

**Comment by bitmill** [comment]
The problem was the following: I did not handle well the case when the response from the server did not contain JSON.

Based on it I updated the "readme" and the script.
